@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDg2MDY2NjQsImlhdCI6MTcwODUyMDI2NCwiaXNzIjoiYmx1ZWJlbGwifQ.ZcGHxr5Y-BooJ1fgDa-gQhjEobTkm7hTrtyX3UAvbCs

### ---------------------------- UPLOAD FEED IMAGES ----------------------------
POST http://localhost:8081/upload_feed_images
Authorization: {{TOKEN}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="my_image.jpg"
Content-Type: image/jpeg

< /Users/anel-bou/Desktop/my_image.jpg
--boundary
Content-Disposition: form-data; name="images"; filename="my_image.jpg"
Content-Type: image/jpeg

< /Users/anel-bou/Desktop/my_image.jpg
--boundary--
### -------------------------------------------------------------------------

###
POST http://localhost:8081/api/v1/upload_image
Authorization: {{TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< /Users/yihaolong/go/src/bluebell/file/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
