POST http://localhost:8081/api/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjowLCJ1c2VybmFtZSI6Imx5aCIsImV4cCI6MTcwNzY0NTUwNSwiaWF0IjoxNzA3NTU5MTA1LCJpc3MiOiJibHVlYmVsbCJ9.jqIgTgLYHqI-l2ODj7tuwGi71a-9LIwihzdliO22RNU
Content-Type: application/json

{
    "community_id": 1,
    "title": "this is title",
    "content": "this is content"
}

