@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDc4OTk3ODQsImlhdCI6MTcwNzgxMzM4NCwiaXNzIjoiYmx1ZWJlbGwifQ.hoacgfzCt8SqW4ng-vDUEGI2nfL_5s94W9pjvyWvzHg

POST http://localhost:8081/api/v1/post
Authorization: Bearer {{TOKEN}}

{
    "community_id": 1,
    "title": "ggg",
    "content": "ggggggg"
}

###
POST http://localhost:8081/api/v1/post
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "community_id": 1,
    "title": "求问2.13.2",
    "content": "这是一个问题2.13.2"
}


###
GET http://localhost:8081/api/v1/post/14689585959276544
Authorization: Bearer {{TOKEN}}

###
GET http://localhost:8081/api/v1/post?page=1&size=100
Authorization: Bearer {{TOKEN}}

###
GET http://localhost:8081/api/v2/post?page=1&size=100&order=score
Authorization: Bearer {{TOKEN}}

###
GET http://localhost:8081/api/v2/community/1/post
Authorization: Bearer {{TOKEN}}
