POST http://localhost:8081/api/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDc2NjAyNDAsImlhdCI6MTcwNzU3Mzg0MCwiaXNzIjoiYmx1ZWJlbGwifQ.HHg9KkIlHAuwhJE1uZi_wskxTWmVwKBJA_vPZFj2jYs
Content-Type: application/json

{
    "community_id": 1,
    "title": "this is title",
    "content": "this is content"
}

###
POST http://localhost:8081/api/v1/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDc2NjAyNDAsImlhdCI6MTcwNzU3Mzg0MCwiaXNzIjoiYmx1ZWJlbGwifQ.HHg9KkIlHAuwhJE1uZi_wskxTWmVwKBJA_vPZFj2jYs
Content-Type: application/json

{
    "community_id": 1,
    "title": "求问",
    "content": "这是一个问题"
}


###
GET http://localhost:8081/api/v1/post/14689585959276544
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDc2NjAyNDAsImlhdCI6MTcwNzU3Mzg0MCwiaXNzIjoiYmx1ZWJlbGwifQ.HHg9KkIlHAuwhJE1uZi_wskxTWmVwKBJA_vPZFj2jYs

###
GET http://localhost:8081/api/v1/post?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDc2NjAyNDAsImlhdCI6MTcwNzU3Mzg0MCwiaXNzIjoiYmx1ZWJlbGwifQ.HHg9KkIlHAuwhJE1uZi_wskxTWmVwKBJA_vPZFj2jYs
