GET http://localhost:8081/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjowLCJ1c2VybmFtZSI6Imx5aCIsImV4cCI6MTcwNzQ2Njg1OSwiaWF0IjoxNzA3NDU5NjU5LCJpc3MiOiJibHVlYmVsbCJ9.7qNj4CJ0c56cTn4DfzcrMNxf4idvjC9qPNxxa21YEoY

###
