GET http://localhost:8081/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjowLCJ1c2VybmFtZSI6Imx5aCIsImV4cCI6MTcwNzUzNTk4OCwiaWF0IjoxNzA3NTM1OTQ4LCJpc3MiOiJibHVlYmVsbCJ9.ZdrvgSIec6ynyt2hoOjM_AX4JWlbQT7iYb_vUXdFaBk

###
