GET http://localhost:8081/api/v1/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMzU5ODA4MjUzNzA5OTI2NCwidXNlcm5hbWUiOiJseWgiLCJleHAiOjE3MDc2NjAyNDAsImlhdCI6MTcwNzU3Mzg0MCwiaXNzIjoiYmx1ZWJlbGwifQ.HHg9KkIlHAuwhJE1uZi_wskxTWmVwKBJA_vPZFj2jYs

###
